### ISSUE TITLE
Problems running examples using python2

### ISSUE THREAD

**Issue by jviereck** [robotlearn/raisimpy#9]
When running the robotics examples after compiling with python2.7, I am getting the following error:

```
examples/robots$ ipython2 anymal_lambda.py 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/jviereck/dev/raisim_workspace/raisimpy/examples/robots/anymal_lambda.py in <module>()
     62     world.set_time_step(0.0025)
     63 
---> 64     vis = raisim.OgreVis.get()
     65 
     66     # these methods must be called before initApp

TypeError: unbound method get() must be called with OgreVis instance as first argument (got nothing instead)
```

This is after installing the raisim lib, visualizer, compiling pybind11 with python2.7 and compiling raisimpy with python2.7.

When I recompile pybind11 with python 3.5 and also raisimpy with python 3.5, the error goes away.

Does someone has an idea what the problem could be?

**Comment by bdelhaisse** [comment]
Hi,

Thanks for reporting that error. It has been fixed now; Python was complaining because `OgreVis`was not instantiated, as such accessing a method is usually not allowed. The thing is `OgreVis` is a singleton so you shouldn't instantiate it, so I fixed it by declaring the function `get` static in `pybind11` (see corresponding commit).

Best,
Brian

**Comment by jviereck** [comment]
Thanks for the quick fix. I am able to launch the `anymal_lambda.py` script using python2.7 now.
